FROM arm64v8/golang:1.18 as builder
#ensure private repo is accessible
#RUN apt-get update && apt-get install -y \
#  ssh-keyscan
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan gitlab.int.tsum.com >> ~/.ssh/known_hosts
RUN git config --global url.'git@gitlab.int.tsum.com:'.insteadOf 'https://gitlab.int.tsum.com/'
#install debugger
RUN go install github.com/go-delve/delve/cmd/dlv@latest
#download packages
WORKDIR /app
COPY ./go.mod ./go.sum .
RUN --mount=type=ssh --mount=type=cache,id=go_cache,target=/go/pkg/mod go mod download
#build server
COPY . .
RUN --mount=type=cache,id=go_cache,target=/go/pkg/mod CGO_ENABLED=0 GOOS=linux go build -gcflags='all=-N -l' ./cmd/offer-read/main.go

FROM arm64v8/golang:1.18
COPY --from=builder /app/main main
COPY --from=builder /go/bin/dlv /go/bin/dlv

CMD /go/bin/dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./main
