services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile_debug
      ssh:
        - default
    ports:
      - 11808:8080
      - 2345:2345
    environment:
      ELASTIC_APM_SERVICE_NAME: offer-read-service
      ELASTIC_APM_SERVER_URL: 'http://elk-dev01.int.tsum.com:8200'
      ELASTIC_APM_ENVIRONMENT: development
      ELASTIC_ADDRESSES: ''
    security_opt:
      - "seccomp:unconfined"
  grpcui:
    image: preowned-grpcui:1
    build:
      context: docker/grpcui
    volumes:
      - ./proto:/proto
    ports:
      - 11802:11802
    environment:
      GRPCUI_ARGS: '-vvv'
      GRPCUI_SERVER: 'app:9090'
      GRPCUI_PORT: 11802
    restart: on-failure
    depends_on:
      - app

volumes:
  pgdata:
    driver: local
